In [1]:
# Импортируем модуль pandas
import pandas as pd 

diabetes = pd.read_csv('data/recipes.csv')
display(diabetes.head())
diabetes.tail()

,id,cuisine,ingredients,slaw mix,jalapeno chilies,fresh tarragon,roasted garlic,powdered sugar,cream of chicken soup,peaches,...,hot chili,pizza crust,onions,pimentos,organic sugar,catfish fillets,sourdough loaf,water chestnuts,amchur,steel-cut oats
0,10259,greek,9,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,25693,southern_us,11,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,20130,filipino,12,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,22213,indian,4,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,13162,indian,20,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False

,id,cuisine,ingredients,slaw mix,jalapeno chilies,fresh tarragon,roasted garlic,powdered sugar,cream of chicken soup,peaches,...,hot chili,pizza crust,onions,pimentos,organic sugar,catfish fillets,sourdough loaf,water chestnuts,amchur,steel-cut oats
495,1121,chinese,9,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
496,18376,italian,8,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
497,17815,italian,8,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
498,32878,southern_us,19,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
499,24410,british,17,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False