In [38]:
import pandas as pd

# # загрузка
# ratings1 = pd.read_csv('data/ratings1.csv', sep=',')
# ratings2 = pd.read_csv('data/ratings2.csv', sep=',')
# dates = pd.read_csv('data/dates.csv', sep=',')
# movies = pd.read_csv('data/movies.csv', sep=',')#, index_col='movieId')

# # объединение 1 с 2 по столбцам
# ratings = pd.concat([ratings1, ratings2],ignore_index=True)

# # Удаление дублеката
# ratings = ratings.drop_duplicates(ignore_index=True)

# # объединение 1-2 с 3 по строкам
# ratings_dates = pd.concat([ratings, dates], axis=1)

# # объединение 1-3 с 4 по индексов филимов
# merged2 = ratings_dates.merge(
#     movies,
#     on='movieId',
#     how='outer'
# )
# # print('Число строк в таблице merged2: ', merged2.shape[0])
# # display(merged2.tail())

In [57]:
covid_data = pd.read_csv('data/covid_data.csv')
display(covid_data.head())
# covid_data.shape
# covid_data['date']=pd.to_datetime(covid_data['date'],dayfirst=True)
# covid_data['date'].describe()
# covid_data.info()

         date province/state country  confirmed  deaths  recovered
0  01/22/2020          Anhui   China        1.0     0.0        0.0
1  01/22/2020        Beijing   China       14.0     0.0        0.0
2  01/22/2020      Chongqing   China        6.0     0.0        0.0
3  01/22/2020         Fujian   China        1.0     0.0        0.0
4  01/22/2020          Gansu   China        0.0     0.0        0.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   date            306429 non-null  object
 1   province/state  228326 non-null  object
 2   country         306429 non-null  object
 3   confirmed       306429 non-null  float64
 4   deaths          306429 non-null  float64
 5   recovered       306429 non-null  float64
dtypes: float64(3), object(3)
memory usage: 14.0+ MB

In [66]:
vaccinations_data = pd.read_csv('data/country_vaccinations.csv')
vaccinations_data = vaccinations_data[
    ['country', 'date', 'total_vaccinations', 
     'people_vaccinated', 'people_vaccinated_per_hundred',
     'people_fully_vaccinated', 'people_fully_vaccinated_per_hundred',
     'daily_vaccinations', 'vaccines']
]
# vaccinations_data.head(3)
# vaccinations_data.shape
# vaccinations_data['date']=pd.to_datetime(vaccinations_data['date'],yearfirst=True)
# vaccinations_data['date'].describe()
display(vaccinations_data.head())

,country,date,total_vaccinations,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,vaccines
0,Afghanistan,2021-02-22,0.0,0.0,0.0,NaN,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."
1,Afghanistan,2021-02-23,NaN,NaN,NaN,NaN,NaN,1367.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."
2,Afghanistan,2021-02-24,NaN,NaN,NaN,NaN,NaN,1367.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."
3,Afghanistan,2021-02-25,NaN,NaN,NaN,NaN,NaN,1367.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."
4,Afghanistan,2021-02-26,NaN,NaN,NaN,NaN,NaN,1367.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."

In [105]:
covid_data = covid_data.groupby(
    ['date', 'country'], 
    as_index=False
)[['confirmed', 'deaths', 'recovered']].sum()
# display(covid_data)
# covid_data.info()

            date             country  confirmed  deaths  recovered
0     2020-01-22               China      547.0    17.0       28.0
1     2020-01-22           Hong Kong        0.0     0.0        0.0
2     2020-01-22               Japan        2.0     0.0        0.0
3     2020-01-22            Kiribati        0.0     0.0        0.0
4     2020-01-22               Macau        1.0     0.0        0.0
...          ...                 ...        ...     ...        ...
86780 2021-05-29             Vietnam     6908.0    47.0     2896.0
86781 2021-05-29  West Bank and Gaza   307838.0  3492.0   300524.0
86782 2021-05-29               Yemen     6731.0  1319.0     3399.0
86783 2021-05-29              Zambia    94751.0  1276.0    91594.0
86784 2021-05-29            Zimbabwe    38933.0  1594.0    36578.0

[86785 rows x 5 columns]

In [60]:
covid_data['date'] = pd.to_datetime(covid_data['date'])

In [61]:
covid_data['active'] = covid_data['confirmed'] - covid_data['deaths'] - covid_data['recovered']

In [62]:
covid_data = covid_data.sort_values(by=['country', 'date'])
covid_data['daily_confirmed'] = covid_data.groupby('country')['confirmed'].diff()
covid_data['daily_deaths'] = covid_data.groupby('country')['deaths'].diff()
covid_data['daily_recovered'] = covid_data.groupby('country')['recovered'].diff()

In [64]:
# covid_data.tail()
covid_data.head()

,date,country,confirmed,deaths,recovered,active,daily_confirmed,daily_deaths,daily_recovered
11337,2020-02-24,Afghanistan,1.0,0.0,0.0,1.0,NaN,NaN,NaN
11570,2020-02-25,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0
11807,2020-02-26,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0
12051,2020-02-27,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0
12299,2020-02-28,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [68]:
vaccinations_data['date'] = pd.to_datetime(vaccinations_data['date'])

3.1

In [103]:
covid_data['date'].describe()

count                            86785
mean     2020-10-15 20:19:34.931151616
min                2020-01-22 00:00:00
25%                2020-06-25 00:00:00
50%                2020-10-17 00:00:00
75%                2021-02-07 00:00:00
max                2021-05-29 00:00:00
Name: date, dtype: object

3.2

In [69]:
vaccinations_data['date'].describe()

count                            42795
mean     2021-05-21 12:12:46.182965248
min                2020-12-02 00:00:00
25%                2021-04-02 00:00:00
50%                2021-05-26 00:00:00
75%                2021-07-15 00:00:00
max                2021-09-06 00:00:00
Name: date, dtype: object

3.3

In [89]:
# vaccinations_data.head()
covid_df=covid_data.merge(vaccinations_data,how='left',on=['date','country'])#'inner' 'outer'
print(covid_df.shape)
display(covid_df.head())
display(covid_df.tail())

(86785, 16)

,date,country,confirmed,deaths,recovered,active,daily_confirmed,daily_deaths,daily_recovered,total_vaccinations,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,vaccines
0,2020-02-24,Afghanistan,1.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-25,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-26,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-27,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-28,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,date,country,confirmed,deaths,recovered,active,daily_confirmed,daily_deaths,daily_recovered,total_vaccinations,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,vaccines
86780,2020-03-12,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86781,2020-03-14,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86782,2020-03-15,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86783,2020-03-16,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86784,2020-03-17,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

3.4

In [99]:
covid_df['death_rate']=covid_df['deaths']/covid_df['confirmed']*100
covid_df['recover_rate']=covid_df['recovered']/covid_df['confirmed']*100
# covid_df.loc[::150,['confirmed','recovered','deaths','death_rate','recover_rate']]

covid_df[covid_df['country']=='United States']['death_rate'].max().round(2)

7.19

3.5

In [102]:
covid_df[covid_df['country']=='Russia']['recover_rate'].mean().round(2)

67.06

date — дата наблюдения;
province/state — наименование провинции/штата;
country — наименование страны;
confirmed — общее число зафиксированных случаев на указанный день;
deaths — общее число зафиксированных смертей на указанный день;
recovered — общее число выздоровлений на указанный день.

country — наименование страны;
date — дата наблюдения;
total_vaccinations — общее число введённых вакцин в стране на указанный день;
people_vaccinated — общее число привитых первым компонентом в стране на указанный день;
people_vaccinated_per_hundred — процент привитых первым компонентом в стране на указанный день (рассчитывается как );
people_fully_vaccinated — общее число привитых вторым компонентом в стране на указанный день (первый компонент уже был введён им ранее);
people_fully_vaccinated_per_hundred — процент привитых вторым компонентом в стране на указанный день (рассчитывается как );
daily_vaccination — ежедневная вакцинация (число вакцинированных в указанный день);
vaccines — комбинации вакцин, используемые в стране.

In [104]:
covid_df.to_csv('data/covid_df.csv', index=False, sep=',')

Оренбург смертей

In [41]:
# covid_data['country'].value_counts()
# covid_data['province/state'].nunique()
covid_rus=covid_data[covid_data['country']=='Russia']
# covid_rus['province/state'].value_counts()
# covid_rus['province/state'].nunique()
# list(covid_rus['province/state'].value_counts().index)
covid_rus_oren=covid_rus[covid_rus['province/state']=='Orenburg Oblast']
covid_rus_oren['deaths'].sum()

121449.0

Челябинск

In [42]:
# list(covid_rus['province/state'].value_counts().index.sort_values())
covid_rus_chel=covid_rus[covid_rus['province/state']=='Chelyabinsk Oblast']
covid_rus_oren['deaths'].sum()

121449.0